# Generated by Django 3.2 on 2022-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='line',
            new_name='fa',
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('content', models.TextField()),
                ('words', models.ManyToManyField(to='app.Word')),
            ],
        ),
    ]
