# Generated by Django 3.2 on 2022-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220903_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='all_words',
            field=models.ManyToManyField(related_name='all_texts_set', to='app.Word'),
        ),
    ]
