# Generated by Django 3.2 on 2022-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_text_all_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
