# Generated by Django 3.2 on 2022-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_text_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='words',
        ),
        migrations.AddField(
            model_name='text',
            name='words_aq',
            field=models.ManyToManyField(related_name='words_aq_text', to='app.Word'),
        ),
        migrations.AddField(
            model_name='text',
            name='words_bq',
            field=models.ManyToManyField(related_name='words_bq_text', to='app.Word'),
        ),
        migrations.AlterField(
            model_name='text',
            name='all_words',
            field=models.ManyToManyField(related_name='all_words_text', to='app.Word'),
        ),
    ]
