# Generated by Django 3.2 on 2022-09-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220920_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='words_aq',
        ),
        migrations.RemoveField(
            model_name='text',
            name='words_bq',
        ),
        migrations.AddField(
            model_name='text',
            name='words_ik',
            field=models.ManyToManyField(related_name='words_ik_text', to='app.Word'),
        ),
    ]
